const Color = {
  PRIMARY_MAIN_COLOR: '#2DB6A3',
  SECOND_MAIN_COLOR: '#22C7A9',
  THIRD_MAIN_COLORL: '#ECFFFC',
  BACKGROUND_DETAIL: '#D7EFE6',
  BACKGROUND_MAIN: '#90E9D9',
  PRIMARY_BUTTON: '#22C7A9',
  BUTTON_AUTH: '#DFB497',
  WHITE: '#FFFFFF',
  BLACK: 'black',
};

export {Color};
